title: "Himanshu Singh"
description: "Personal profile website"
baseurl: "/himanshu-singh" # subpath for GitHub Pages project site
url: "https://hsinghweb.github.io" # root domain for the user/organization

markdown: kramdown
permalink: pretty

nav:
  - title: "About"
    url: "/#about"
  - title: "Resume"
    url: "/resume"
  - title: "Skills"
    url: "/#skills"
  - title: "Technical Insights"
    url: "/trino"
  - title: "Contact"
    url: "/#contact"

plugins:
  - jekyll-feed
  - jekyll-seo-tag